name: Crowdin Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync translations with Crowdin
        uses: crowdin/github-action@v2.7.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: >
            New Crowdin translations by
            [Crowdin GitHub Action](https://github.com/crowdin/github-action)
          pull_request_base_branch_name: 'main'
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
